### ISSUE TITLE
Hardware Nat on TP-link Archer C7 v1

### ISSUE THREAD

**Issue by bardimnik** [gwlim/mips24k-lede-patch#1]
Hello! This patch is suitable for inclusion Hardware Nat on TP-link Archer C7 v1?

**Comment by bardimnik** [comment]
Hello! Can you make a minimal firmware with the ability to connect and mount usb and enable Hardware Nat for the TP-Link Archer C7 v1? Please.

**Comment by gwlim** [comment]
@bardimnik
https://github.com/gwlim/Fast-Path-LEDE-OpenWRT/tree/master/Fast-Path/Aug-2017
No extroot though
