### ISSUE TITLE
deployment on barrier breaker 1407?

### ISSUE THREAD

**Issue by tacuar** [gwlim/mips24k-lede-patch#10]
noticed that your repositories appear to have some old patches for barrier breaker.

If i want to apply your patch script on bb1407, what modifications would need to be done in local?

**Comment by gwlim** [comment]
I already abandoned barrier breaker
1)If there is a security vulnerability in 1 component NOBODY will patch it unless you do it yourself which is really tedious, remember Krack?
2)barrier breaker is using Kernel 3.10 which is EOL again if there is a security vulnerability NOBODY will patch it unless you do it yourself which is really tedious

Performance is worthless without security.

**Comment by tacuar** [comment]
@gwlim  Got it, seems reasonable regarding the wireless security.

But i really hope to have an idea from you and learn the method of modification if i want to patch it.

For example, the cc15051, or, lede-master, the kernel keeps changing, under target-linux-generic, the folders keeps changing, config-3.10, config-3.18, now to config-4.9, etcs.....

Please please please Gwlim..... Could you???

I really would appreciate it a lot if you have an archive patch file somewhere which you had before when you were still on BB at that time.
