### ISSUE TITLE
very new guy asking Lord GWLIM for help

### ISSUE THREAD

**Issue by tacuar** [gwlim/mips24k-lede-patch#3]
Esteemed GWLIM,

Thank you for your time. will it be workable if i apply your mips24k-ar71xx-lede-patch on this below router?

I know the platform is different, i am very new guy, but i really want to apply your GREAT patch!!!!!

Hope to get your instruction :+1: 

Model: PSG1208
Platform: MediaTek MT7620A
Target: ramips
Instruction Set: MIPS32
Sub Instruction Set: MIPS32 24K/E series
Bootloader: MyLoader
CPU MHz: 580
Flash MB: 8
RAM MB: 64
Ethernet 100M ports: 5
Switch: MediaTek MT7620A
Modem: No
VLAN: Yes
WLAN Hardware: MediaTek MT7620A, MT7612E
WLAN 2.4GHz: b/g/n
WLAN 5.0GHz: a/n/ac
WLAN Comments: K2(PSG1218), External PA+LNA on both WLAN2.4 and WLAN5

**Comment by tacuar** [comment]
i saw your discussions on that forum and lots of guys feeded back that the wireless throughout increased dramatically after applying your patch. and you said this patch is very platform independent. so i only kind of hope this routher, even with MTK might also be working.

**Comment by gwlim** [comment]
Yours is a 100Mbps Router.
Your Router should be already able to saturate 100Mbps even without Fast Path

**Comment by tacuar** [comment]
Thank you very much for your response GWLIM.

Yes it is a 100M X 4LANS : )

The reason i 'm still curious is because i saw your remarks in the forum saying that the wireless throughout will increase dramatically after applying this fast path. 

GWLIM, if i install something that will consume some ram of this router, and if i install fast path on this routher, will it increase the wireless download performance?

**Comment by gwlim** [comment]
If you check the example I am referring to Gigabit Router with weak cpu, like WR1043ND V1, it has Gigabit & wifi but because of NAT wifi performance is reduced.
But for your case your WiFi performance is limited by the 100Mbps port

**Comment by tacuar** [comment]
got it and again, i'm very grateful for your kind response.

I got one wndr3800 (is ar71xx same like your 4300), i suppose the patch i need to apply is the "mips24k-ar71xx-lede-patch" , am i correct?

Plus, these days your updates are very active. Thus if i patched already your previous one, do i need delete the current LEDE whole source folder and re-git a clean source to apply your latest patch?

**Comment by gwlim** [comment]
wndr3800 is MIPS24k so use "mips24k-ar71xx-lede-patch"

Yes re-git and reapply.

**Comment by tacuar** [comment]
Okey got it and many thanks! i will do that now. by the way, i'm kind of curious all your patches here are device specific, for ar71xx, and even have two different patched for mips74k and mips_24kc.

for example , if i apply your mips_24k patch on the new git source and apply, but if i select other devices with other architecture, will the generated bins be having the increased and optimized NAT performance?

you have in your hands the specific model and you optimized them with a corresponding patch, do we have a patch which is not specific "designed" for a specific device?

**Comment by gwlim** [comment]
Only if the target image is mips24k and is a ar71xx atheros chip

**Comment by tacuar** [comment]
oh okey i got it.

then it means that this is for ar71xx only, not just have to match the mips24k, but also have to be a model with ar71xx atheros chip.

hope to see your updates here and see a patch version applicable for all architectures, even not very optimized.

thanks again for your great works!
